### ISSUE TITLE
Prime error

### ISSUE THREAD

**Issue by tigerxu** [veg/hyphy#856] opened 2018-11-01 09:42 UTC
Hi Dr. Pond,

Report an issue when running prime analysis on the DataMonkey server online (http://classic.datamonkey.org). I tried several times and got the message below

This error has been reported to the datamonkeys responsible for this. Sorry, we will fix the issue as soon as possible. In the meantime, it may be worthwhile rerunning your analysis to see if the condition is transient.

I have performed the other analysis FEL, MEME, SLAC. All these run well.
http://classic.datamonkey.org/cgi-bin/datamonkey/showdata.pl?upload.557813217722089.1
http://classic.datamonkey.org/cgi-bin/datamonkey/showdata.pl?upload.557813217722089.1.aa

Many thanks for helping look at it!

Zhuofei

**Comment by rdvelazquez** [comment] 2018-11-01 11:32
Dear @tigerxu,

Thank you for the additional information about the issue you are experiencing with PRIME. I will be looking into what's going on with PRIME today. I'm going to close this github issue now as it is a duplicate of #824. I will reopen issue #824, reference your comment above in that issue and track all the discussions regarding this instance of PRIME not working in that github issue.

Best,
Ryan

**Closed by rdvelazquez** 2018-11-01 11:32 UTC
