### ISSUE TITLE
Conflicting RELAX results

### ISSUE THREAD

**Issue by flopezo** [veg/hyphy#817] opened 2018-07-10 01:40 UTC
Hello,

I'm doing a RELAX analysis and getting contradictory results. Using the same alignment and test branch, sometimes the results indicate evidence for relaxation and other times for intensification. 

I'm selecting a single test branch in this analysis, so I was wondering if that's the reason for this unstable behavior.

Here are two examples.
Relaxation: http://test.datamonkey.org/relax/5b44072bcbe0c7233dc50c12
Intensification: http://test.datamonkey.org/relax/5b440a4dcbe0c7233dc50c4d

I would appreciate any help.

**Comment by spond** [comment] 2018-07-10 01:46
Dear @flopezo,

I am aware of this issue and am working on a solution, because other people have reported the same problem. 

Best,
Sergei

**Comment by flopezo** [comment] 2018-07-10 02:08
Dear Sergei,

Thank you for your prompt reply. I tried selecting three branches (two sister tips and an internal branch) and observed the same instability issues. I look forward to a future version of RELAX including a solution.

All the best,

Federico

**Comment by spond** [comment] 2018-07-12 07:15
Dear @flopezo,

I have posted a partial fix in the c193cadae876ad9779e282adf10a464c7a28367d commit. The issue is that RELAX fits a complex mixture model, which can and does often have more than one local maximum, implying that the optimization can converge to different maxima in different runs. The randomness arises from multithreaded execution of HyPhy, where different runs will accumulate slightly different results over time, because in floating point arithmetic a + b ≠ b + a, and the result of floating point computations that are multithreaded can **stochastically** depend on the order in which parallel threads return their results. For well-conditioned problems, this randomness is not an issue because the single global maximum for the likelihood function is reliably found.

The problem is further exacerbated when a single branch is in the test (or the reference set), because there is generally little signal to be extracted from it, and the likelihood surface is flat. 

My fix does a few things

1. Makes tweaks to the optimization procedure and model parameterization to try to improve convergence.
2. Adds checks to diagnose potential convergence issues. This works by adding a step after the alternative RELAX model has been fitted as follows
2.1. Compute the likelihood function on a grid of K-values from 0 to 5. 
2.2. If the difference between the best score for K > 1 and K < 1 is too small (<5 likelihood points), then do 2.3
2.3 If K was estimated to be > 1, then force it to be < 1 and reestimate the alternative model (and similarly set K > 1 if it was estimated to be < 1). If the resulting model has a better fit, accept it.
2.4. In either case, print a warning to the the user 

Steps 2.2 and 2.3 will at least work to consistently estimate K on the right side of 1.

Hope this helps,
Sergei

PS @stephenshank and @stevenweaver; this is a priority fix that needs to be pushed to datamonkey.

**Comment by spond** [comment] 2018-07-19 19:46
Dear @flopezo,

You are correct. The conda package will be updated with the next version release (NB @stevenweaver)

Best,
Sergei

**Comment by stephenshank** [comment] 2018-07-24 20:58
Dear @flopezo,

We've deployed the latest version of RELAX to our "staging" instance:

http://staging.datamonkey.org/

which is where we test new code before releases. If you're still interested, we would definitely like to hear about your experience with the new version of RELAX, and whether you continue to experience the issue that you've raised.

Best,
Stephen

**Comment by flopezo** [comment] 2018-07-25 14:46
I sent you the input and log files via e-mail. Thank you, Sergei.

**Comment by flopezo** [comment] 2018-07-25 15:04
I forgot to mention that the error is not always reproducible. I ran RELAX a few times with the same alignment and sometimes it ran successfully to completion.

**Comment by spond** [comment] 2018-07-25 15:11
Dear @flopezo,

What system are you running HyPhy on? Specifically

1. Which compiler do you have?
2. Are you using multithreading?
3. Which processor (AMD or Intel, and which CPU model) are you using?

We've had some very odd issues with AMD Epyc CPUs that we are still tracking down that resulted in similar _stochastic_ errors.

Best,
Sergei

**Comment by flopezo** [comment] 2018-07-25 15:56
Dear Sergei,

I'm running HyPhy on a cluster running CentOS 7 x86_64:
1. I'm using the [conda compiler tools](https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html) - GCC v7.2.0.
2. Yes, I am using multithreading.
3. Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz.

And here is the cmake and make output printed to screen when I built HyPhy.
[hyphy_build.log](https://github.com/veg/hyphy/files/2228575/hyphy_build.log)

I will try running RELAX again with other alignments that caused the same error.

**Comment by flopezo** [comment] 2018-07-26 00:51
Dear Sergei,

I tried running RELAX on the "staging" instance with an alignment that resulted in `Internal error in _LikelihoodFunction::ConjugateGradientDescent.` and it seems to get stuck while fitting the alternative model. Here is the job id:

http://staging.datamonkey.org/relax/5b5906e3874df36d33e05396

Moreover, I ran RELAX locally several times with the same alignment, and it crashed with the error above or reported either evidence or no significant evidence for relaxation. I used the alignment I sent you via e-mail earlier today. 

Any help would be greatly appreciated.

Best,

Federico

**Comment by kmeusemann** [comment] 2019-04-13 08:54
Hi all, has this been solved with 2.4.0-alpha?
Best Karen

**Comment by spond** [comment] 2019-04-13 12:06
Dear @flopezo and @kmeusemann,

Yes, this has been resolved in 2.4.0-alpha. I confirmed that the problematic dataset now runs fine. Note that this has not yet been pushed to the main production instance of data monkey, and will appear there when we release 2.4 in the next month or so.

Best,
Sergei

**Closed** 2019-07-22 14:52 UTC
Labels: bug, methodology/applications
