### ISSUE TITLE
Fixing HyPhy installation issue on Ubuntu 14.04

### ISSUE THREAD

**Issue by clairemcwhite** [veg/hyphy#369] opened 2015-12-17 22:41 UTC
I recently had trouble installing hyphy-2.2.6 on my Ubuntu machine, and I wanted to share my fix here. 

$ cmake ./ worked fine, 

however, $ make MP2 did not:

"...
/usr/bin/ld: cannot find -lcrypto 
/usr/bin/ld: cannot find -lssl 
collect2: 
error: ld returned 1 exit status 
make[3]: *** [HYPHYMP] Error 1 
make[2]: *** [CMakeFiles/HYPHYMP.dir/all] Error 2 
make[1]: *** [CMakeFiles/MP2.dir/rule] Error 2 
make: *** [MP2] Error 2"

The change in CMakeLists.txt suggested for a similar problem in http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1322414552 had no effect. However, following that suggestion, I changed line 301 in CMakeLists.txt to:
target_link_libraries(HYPHYMP crypto curl pthread ssl dl)

Then $ make MP2 followed by $ make install worked fine. 

Claire

**Comment by stevenweaver** [comment] 2015-12-18 00:33
Hello Claire,
Thank you for bringing this to our attention. 

Using : 
* Ubuntu 15.04
* cmake 3.0.2

I'm able to compile the `MP2` target. 
May I ask which versions you are using? You can find them by typing the commands:

```
lsb_release -a
cmake -version
```

Thanks,
Steven

**Comment by clairemcwhite** [comment] 2015-12-18 01:10
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

cmake version 3.4.1

Claire

**Comment by stevenweaver** [comment] 2016-02-23 18:10
Could not reproduce on our local ubuntu installation. Closing for now. Please feel free to reopen if the issue continues.

**Closed by stevenweaver** 2016-02-23 18:10 UTC
Labels: Bug
