### ISSUE TITLE
FEL: error processing your job

### ISSUE THREAD

**Issue by mdbohorqueza** [veg/hyphy#1438] opened 2021-12-11 00:52 UTC
Hello,

FEL is showing this when I try to process two GARD-results files:

We're sorry, there was an error processing your job. Please try again, or visit
our GitHub issues page
and create an issue if the issue persists.
Standard Error Message
openmpi/gnu(3):ERROR:105: Unable to locate a modulefile for 'openmpi/gnu/3.0.2'
/var/spool/torque/mom_priv/jobs/1903180.new-silverback.SC: line 37: mpirun: command not found

This is the URL: https://www.datamonkey.org/fel/61b3a502652a48728e6357c7

What could have been the problem?

Thanks in advance,
Regards.

**Comment by spond** [comment] 2021-12-11 15:08
Dear @mdbohorqueza ,

We are in the process of a major cluster upgrade, and it seems like there are some "growing pains" with the Datamonkey service. We will attempt to resolve them as quickly as possible. Stay tuned.

Best,
Sergei

**Comment by stevenweaver** [comment] 2021-12-11 18:37
Dear @mdbohorqueza, 

We performed maintenance on our computing cluster that resulted in a disruption of services. The site should be operating as expected now. 

Best,
Steven

**Comment by stevenweaver** [comment] 2021-12-11 18:38
Duplicate of #1437

**Closed by stevenweaver** 2021-12-11 18:38 UTC

**Comment by mdbohorqueza** [comment] 2021-12-12 03:20
Dear Sergei and Steven,
Thanks for the answer. I'll try again.
