### ISSUE TITLE
aBSREL: is it possible to get omega, dN and dS values separately?

### ISSUE THREAD

**Issue by IvanJakovlic** [veg/hyphy#1198] opened 2020-08-17 07:48 UTC
Dear developers, we are using aBSREL on a large dataset. So far it performed great, possibly with a bit more reliable results than PAML (bu only using the 'double+triple' parameter), and much faster than the latter program. However, unlike PAML, aBSREL reports only omega values, and we need dN and dS values as well to test specific hypotheses. We tried running PAML, but it seems that it may take months to complete a run on our dataset.  
Therefore, we wonder if it may be possible to obtain separate dN, dS and omega values in aBSREL?

**Comment by spond** [comment] 2020-08-17 13:13
Dear @IvanJakovlic,

dS and dN are derivative quantities (see 1.4.1 and references therein from http://www.hyphy.org/resources/hyphybook2007.pdf). Remember that aBSREL also fits a distribution of &omega; at each branch, so there are several ways to define dN and dS: mean over all rates, separate values for each rate, etc. Which model do you want to obtain dN and dS for? I'd need to add a bit more code to `aBSREL.bf` to report out some estimates of dN and dS.

Finally, can you explain a bit more why you need dS and dN? I am just trying to understand if that's a common enough use-case to make the calculations a part of the optional parameters in the distribution.

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-08-17 14:48
Dear Sergei,

I am trying to disentangle signals of adaptive (purifying selection) an nonadaptive (mitochondrial architecture-driven mutations) evolution in a large number of mitochondrial genomes. I am also trying to assess whether population size affects the evolutionary rate. 
Following the logic outlined by Lanfear et al. (2010), having dN and dS values, along with the omega, may be helpful in identifying differences in relative contributions of these variables between different lineages: " Because dS estimates the number of “silent” substitutions that do not change the amino acid sequence, it will be predominantly influenced by the mutation rate; dN estimates the number of substitutions that change the amino acid sequence, which is likely to include both neutral and nearly neutral changes. Because of this, dN is expected to be influenced both by the mutation rate and by population size. ω is expected to be influenced by selection and effective population size, but not the mutation rate. " 
Lanfear et al. (2010) Mutation rate is linked to diversification in birds. PNAS 107:20423–20428. https://doi.org/10.1073/pnas.1007888107 
I was also wondering whether the sum of dN and dS could produce a meaningful estimate of the overall evolutionary rate.
I understand that there are multiple ways to define and calculate these values, and that they will depend on the way they are calculated.
I guess that means over all rates would be the value that we need for our objectives. 
Thank you for the prompt response.
Kind regards,
Ivan

**Comment by spond** [comment] 2020-08-17 14:57
Dear @IvanJakovlic,

OK, that takes sense (although to be pedantic, dS and dN do not estimate the numbers of substitutions, but rather the numbers of substitutions **per synonymous/non-synonymous site**). The tricky part is always how to define what is a synonymous site (e.g. see https://pubmed.ncbi.nlm.nih.gov/8583885/); I think for your purposes in may be enough to decompose the branch lengths into synonymous and non-synonymous components, so that the total branch length is the sum of the two. One issue with aBSREL models is that branch lengths will be **very** sensitive to high &omega; if they are present. 

At any rate, I'll add the option to decompose the branch lengths under the full adaptive model and you can tell me if that works for you.

Best,
Sergei

**Comment by spond** [comment] 2020-08-20 13:45
Dear @IvanJakovlic,

In the `develop` branch (see https://github.com/veg/hyphy-analyses/ for installation instructions), you will now see branch lengths under the full adaptive model split off into synonymous and non-synonymous components in the `JSON` output file. For example:

<img width="679" alt="Screen Shot 2020-08-20 at 9 44 50 AM" src="https://user-images.githubusercontent.com/1018513/90777761-dbabe180-e2c9-11ea-849f-645191facb51.png">

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-08-24 11:33
Dear Dr. Pond,
We installed the 'develop' version via the following command:
git clone https://github.com/veg/hyphy.git hyphy-develop
cd hyphy-develop
git checkout develop
cmake [./]
make -j MP
And then we run it via the ‘./HYPHYMP – I’ command
And finally chose aBSREL

However, we did not get the result shown in the screenshot above (in the json file)

![image](https://user-images.githubusercontent.com/45580101/91033837-521b4d00-e604-11ea-8d84-217cf25584b9.png)

The compete file is attached below:
[atp6_out.zip](https://github.com/veg/hyphy/files/5117199/atp6_out.zip)

**Comment by spond** [comment] 2020-08-24 11:47
Dear @IvanJakovlic,

Your sequence of commands is correct and I've committed the changes. Could you confirm that lines 509 and 510 in the file `res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf` are as follows:

```
absrel.stree_info  = trees.ExtractTreeInfo ((absrel.ESEN_trees [terms.fit.synonymous_trees])[0]);
absrel.nstree_info = trees.ExtractTreeInfo ((absrel.ESEN_trees [terms.fit.nonsynonymous_trees])[0]);
```

Best,
Sergei

PS Just curious as to why you are running the interactive (-I) mode instead of `./HYPHYMP absrel --alignment...`

**Comment by IvanJakovlic** [comment] 2020-08-25 07:10
We can confirm that.
 
![image](https://user-images.githubusercontent.com/45580101/91142953-0626e180-e6b2-11ea-8b2c-a60cc2124192.png)

We are running the ‘develop’ version in the interactive mode because we were not sure how to set some of the parameters using command line. Following your suggestion we used this command to run: …/hyphy-develop/HYPHYMP aBSREL --alignment atp6_mafft.fas --code Invertebrate-mtDNA --branches Leaves --multiple-hits Double+Triple
But we did not manage to get separate dN and dS values.

![image](https://user-images.githubusercontent.com/45580101/91142978-10e17680-e6b2-11ea-908e-2c75a02cc611.png)

Regards,
Ivan

**Comment by spond** [comment] 2020-08-25 12:51
Dear @IvanJakovlic,

Thanks for confirming. Must be that the inclusion of 2x and 3x hits breaks something. Let me check.

Best,
Sergei

**Comment by spond** [comment] 2020-08-25 13:33
Dear @IvanJakovlic,

OK, I just confirmed that the 2H + 3H model also outputs the S/NS branch lengths in the current `dev` branch. I don't quite understand what may be causing the issue (other than the program may be picking up an older analysis version). Can you try running 

`./HYPHYMP res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --alignment file --multiple-hits Double+Triple` 

just to be 100% sure that the script file is the most recent one?

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-08-28 19:09
Hi Sergei,
we tried the above command, 
../HYPHYMP ../res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code Echinoderm-mtDNA --alignment atp6_mafft.fas --multiple-hits Double+Triple
but we are getting the following error
![image](https://user-images.githubusercontent.com/45580101/91606479-094bf700-e96a-11ea-804c-d0c7eae5d178.png)

when we use  this command "../HYPHYMP absrel --code Echinoderm-mtDNA --alignment atp6_mafft.fas --multiple-hits Double+Triple", it runs successfully

P.S. I will be away for a week, so I will instruct my colleague, Dong Zhang to keep an eye on the thread and continue the communication if needed.
Thanks,
Ivan

**Comment by spond** [comment] 2020-08-28 20:24
Dear @IvanJakovlic,

Make sure you put quotes around the genetic code, like in the following.

```
../HYPHYMP ../res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code 'Echinoderm-mtDNA' --alignment atp6_mafft.fas --multiple-hits Double+Triple
```

Best,
Sergei

**Comment by dongzhang0725** [comment] 2020-08-29 02:06
Hi Sergei,

We tried the following two codes, but we are still getting the same error.

> ../HYPHYMP ../res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code 'Echinoderm-mtDNA' --alignment atp6_mafft.fas --multiple-hits Double+Triple


> ../HYPHYMP ../res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code "Echinoderm-mtDNA" --alignment atp6_mafft.fas --multiple-hits Double+Triple


![image](https://user-images.githubusercontent.com/15956921/91625888-7b115880-e9dd-11ea-844a-3c4f79fbac49.png)

Thanks,

Dong

**Comment by spond** [comment] 2020-09-02 23:54
Dear @dongzhang0725,

Would it be possible for you to e-mail (or attach here) the `atp6_mafft.fas` file? I am not certain what is causing the error, and I can't reproduce it easily with a few test datasets I've tried.

Best,
Sergei

**Comment by dongzhang0725** [comment] 2020-09-03 00:54
Hi @spond ,

I sent `atp6_mafft.fas` to you via your email (spond@temple.edu), do you receive it?.

Best,
Dong

**Comment by spond** [comment] 2020-09-03 03:11
Dear @dongzhang0725,

Can you try running from the same directory where `hyphy` is installed? I think you may be running into HyPhy
[atp6_mafft.fas.ABSREL.json.zip](https://github.com/veg/hyphy/files/5165904/atp6_mafft.fas.ABSREL.json.zip)
 library version incompatibility.

Also, please download the `develop` branch (see README at https://github.com/veg/hyphy-analyses/) because there is a bug 2.5.18 (will be fixed in the next release) that relates to non-standard genetic codes.

```
./hyphy res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code "Echinoderm-mtDNA" --alignment /path/to/atp6_mafft.fas --multiple-hits Double+Triple
```
I was able to perform the analysis on your data (results attached) with the current `develop` branch.

Best,
Sergei

[atp6_mafft.fas.ABSREL.json.zip](https://github.com/veg/hyphy/files/5165905/atp6_mafft.fas.ABSREL.json.zip)

**Comment by dongzhang0725** [comment] 2020-09-03 07:26
Dear @spond ,

I tried your code, and I succeed to get the `dn` and `ds` values separately. However, when I use `HYPHYMP` program, I can't get `dn` and `ds` values, the command line is listed below.

> mpirun -n 10 ./HYPHYMP res/TemplateBatchFiles/SelectionAnalyses/aBSREL.bf --code "Echinoderm-mtDNA" --alignment ./run/atp6_mafft.fas --multiple-hits Double+Triple --branches Leaves

As our working dataset is big (288 taxa x 13830 sites), so we prefer to use `HYPHYMP` to speed it up, could you help us figure out what  is causing the error for `HYPHYMP` program?

Thanks,
Dong

**Comment by dongzhang0725** [comment] 2020-09-04 08:53
Dear @spond ,

Thank you for your help on `dN` and `dS` calculation.

Now we have another question, can I use the `dN` and `dS` values **(Full adaptive model [non-synonymous subs/site] & Full adaptive model [synonymous subs/site])** to calculate `w (use the formula dN/dS)` value of each branch? Our purpose is to get the `omega` value of each species, like free ratio in PAML.

Thanks,
Dong

**Comment by spond** [comment] 2020-09-04 15:20
Dear @dongzhang0725,

I am a bit confused here; the original goal was to estimate synonymous divergence, not dN/dS. If you wish to extract simple &omega; estimates for individual branches you

1. Can directly read it from the JSON from the `Baseline MG94xREV omega ratio` key. It is estimated directly, and will generally be slightly different from `(Full adaptive model (non-synonymous subs/site))/(Full adaptive model (synonymous subs/site))`, see page 13 of http://www.hyphy.org/resources/hyphybook2007.pdf.
```
 "branch attributes":{
   "0":{
     "Ancyrocephalus_mogurndae_Ancyroc_gurndae":{
       "Baseline MG94xREV":959.8421505957159,
       "Baseline MG94xREV omega ratio":3.651470736565482e-05,
       "Corrected P-value":1,
       "Full adaptive model":833.5457639825622,
       "Full adaptive model (non-synonymous subs/site)":0.1798029541924215,
       "Full adaptive model (synonymous subs/site)":833.365961028368,
       "LRT":0,
       "Nucleotide GTR":0.5645848428372934,
       "Rate Distributions":        [
[4.231437662210101e-05, 1] 
        ],
       "Rate classes":1,
       "Uncorrected P-value":1,
       "original name":"Ancyrocephalus_mogurndae_Ancyroc_gurndae",
       "rate at which 2 nucleotides are changed instantly within a single codon":0.8281495871657801,
       "rate at which 3 nucleotides are changed instantly within a single codon":7.580942874129035
      },
```

2. If **all** you want is a single dN/dS per branch, then aSBREL is an overkill, since it will attempt to infer more complex distributions on individual branches as appropriate.  

3. For some branches, e.g. 

```
 "Tetrancistrum_nebulosi_NC_018031_1":{
       "Baseline MG94xREV":0.3738931874101267,
       "Baseline MG94xREV omega ratio":0.07078050461261605,
       "Corrected P-value":1,
       "Full adaptive model":2.864925567132167,
       "Full adaptive model (non-synonymous subs/site)":0.328029959912319,
       "Full adaptive model (synonymous subs/site)":2.536895607219847,
       "LRT":3.027674523182213,
       "Nucleotide GTR":0.3220387718706055,
       "Rate Distributions":        [
[0.1591098597814587, 0.8216813940432637],
        [6.367966797541969, 0.1783186059567363] 
        ],
       "Rate classes":2,
       "Uncorrected P-value":0.08239022541894209,
       "original name":"Tetrancistrum_nebulosi_NC_018031_1",
       "rate at which 2 nucleotides are changed instantly within a single codon":0,
       "rate at which 3 nucleotides are changed instantly within a single codon":1.04784269529078
      }`
```

you will actually have several dN/dS rates, encoded in 

```
"Rate Distributions":        [
[0.1591098597814587, 0.8216813940432637],
        [6.367966797541969, 0.1783186059567363] 
        ],
```

Representing this with a single dN/dS may lead you to conclude that branches that do evolve differently are actually not evolving differently (see Figure 1.2 in http://www.hyphy.org/resources/hyphybook2007.pdf)

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-09-08 13:10
Dear Dr. Pond, 
Thank you for your responses and for adding the function.
I also apologise for a bit delayed response; as we were trying to figure out on our own the answer to the latest question and toyed around with different analyses.
We need omega, dS and dN values separately, as we are running a multiple regression analysis with multiple independent variables in order to assess how well they explain our dependent variable. 
aBSREL produces baseline omega, for which hyphy book states that:
 
![image](https://user-images.githubusercontent.com/45580101/92477194-75d3bb00-f1e0-11ea-8b65-25449bd26fde.png)



As absolute omega values are not crucial for our analysis, this is fine if the two values are highly correlated (proportional). 
Indeed, when we inferred free-ratio w in PAML on a smaller dataset (the large one runs too slowly), we found a strong positive correlation (0.8-0.9) between the aBSREL baseline omega ratio and PAML omega, from which we inferred that baseline omega is acceptable for our analysis. 

However, in another hyphy github thread (https://github.com/veg/hyphy/issues/391) we found that baseline omega should not be used for inference:
 
![image](https://user-images.githubusercontent.com/45580101/92477235-8f750280-f1e0-11ea-989d-282facdb8c32.png)
![image](https://user-images.githubusercontent.com/45580101/92477265-9ac82e00-f1e0-11ea-8b8a-8fa72e165d48.png)

Now we are wondering whether we can use the baseline aBSREL omega for further analyses. 
Or should we calculate the omega values directly from the dN and dS values produced by the newly added function, and use those for further analyses?
Finally, we also calculated PAML-like free ratio omega using the guidelines in this thread: http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1350619621 (using AnalyzeCodonData.bf)

Therefore, to summarize, we have three choice in total to get omega values in HYPHY,
1. use baseline omega generated by the absrel;
2. use omega inferred using the GY94W9 model in AnalyzeCodonData.bf 
3. use omega calculated from dN and dS values generated by the newly added function (dN/dS) 

Values produced by options 1 and 2 have relatvely high correlation (0.85), but produce somewhat different results in our multiple regression analyses, whereas the third one is still running.

Thanks for your time.
Regards,
Ivan

**Comment by spond** [comment] 2020-09-08 13:20
Dear @IvanJakovlic,

1. aBSREL baseline == free-ratio models, except MG94xREVxCF3x4 vs GY94 (in PAML).  The differences should be minor. 
2. What are you trying to regress on? Can you provide a more detailed explanation. You might actually be able to parameterize the omega rates to depend on covariates, for example as we done for example by [Clark and Aguardo](https://www.researchgate.net/publication/40821819_A_Novel_Method_to_Detect_Proteins_Evolving_at_Correlated_Rates_Identifying_New_Functional_Relationships_between_Coevolving_Proteins). 
3. If all you want are mean dN/dS, `aBSREL` is an overkill (you don't need site-level rate variation), **and** you should definitely take estimation error into account, i.e. obtain "variance" estimates for each dN/dS and include those in your regression analyses (e.g. weighted least squares).

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-09-09 12:01
We tried a number of different options, and decided to go with the aBSREL baseline data. 
It seems to produce a farily reliable result.
Thanks for your help once again.

**Comment by spond** [comment] 2020-09-09 12:19
Dear @IvanJakovlic,

Great. I would encourage you to include some version of variance estimation in the inference, mostly because regression analyses make strong assumptions about error distributions, and dN/dS estimates may not follow them. Linear regression, for example, assumes constant variance for errors, so that the "size" of the `e` term in `y ~ x + e` does not depend on `x`, i.e. `e~1`. For `dN/dS`, variance estimates usually grow with `dN/dS`, so `e ~ x`, which may make things a bit dodgy.

A reasonable way to handle this is to estimate sampling variance of the dN/dS estimator and include it in the regression analysis, via for example, weighted regression. You'll end up with more robust inference that way. If you are interested, I can make some minor changes to `FitMG94` to output these branch level dN/dS **with error estimates**.

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-09-16 10:29
Dear Dr. Pond
Another apology for the long dely. We were not sure whether we will need the variance estimates, so we were trying to figure it out. We are still learning how to use BRMS, so as yet we're not sure how to include variance estimation.
Currently we are finding the best-fit regression methods. The inclusion of dN and dS variables produced results that are in agreement with theoretical expectations, so it seems the results may be acceptable.
We still remain uncertain whether we will need error estimates.  If needed, we will contact you again.
Thanks again,
Ivan

**Comment by IvanJakovlic** [comment] 2020-09-16 10:30
Dear Dr. Pond
Another apology for the long delay. We were not sure whether we will need the variance estimates, so we were trying to figure it out. We are still learning how to use BRMS, so as yet we're not sure how to include variance estimation.
Currently we are finding the best-fit regression methods. 
The inclusion of dN and dS variables produced results that are in agreement with theoretical expectations, so it seems the results may be acceptable.
We still remain uncertain whether we will need error estimates. If needed, we will contact you.
Thanks again,
Ivan

**Comment by spond** [comment] 2020-09-17 11:22
Dear @IvanJakovlic,

Let me know what you find. One possibility you might consider is variance stabilizing transformation (e.g. take the square root of dN and dS prior to regressing the data), of dN/dS or specifying measurement error (http://search.r-project.org/library/brms/html/me.html), although it's not quite what you want. I am sure in something as general as `BRMS` you should be able to do something more complex; I am just not that familiar with the code. I would, however, by particularly careful with "censored" estimates, i.e. very large dN or dS values, which usually are very imprecise.

In any case, you can use [FitMG94](https://github.com/veg/hyphy-analyses/tree/master/FitMG94), with the following options

```
hyphy FitMG94.bf --alignment /path/to/atp6_mafft.fas --type local --code "Echinoderm-mtDNA" 
```

The resulting JSON will be written to `/path/to/atp6_mafft.fas.FITTER.json` and in it you will find entires like:

```
   "0":{
     "Ancyrocephalus_mogurndae_Ancyroc_gurndae":{
       "Confidence Intervals":{
         "LB":8.267092031960146e-05,
         "MLE":0.0001048669837763638,
         "UB":0.0001315079819280161
        },
       "Nucleotide GTR":0.5646366930236583,
       "Standard MG94":826.6533326905305,
       "nonsynonymous":0.2742131458504463,
       "original name":"Ancyrocephalus_mogurndae_Ancyroc_gurndae",
       "synonymous":826.3791195446806
      },
     "Benedenia_hoshinai_NC_014591_1":{
       "Confidence Intervals":{
         "LB":0.2208915236247295,
         "MLE":0.3291554843643744,
         "UB":0.4661701189925868
        },
       "Nucleotide GTR":0.1860458840525351,
       "Standard MG94":0.1787671520206324,
       "nonsynonymous":0.09120181469800782,
       "original name":"Benedenia_hoshinai_NC_014591_1",
       "synonymous":0.08756533732262452
      }
```

`Confidence Intervals` is the record of branch specific `dN/dS` estimate, with the corresponding lower and upper bound. For example, at `Benedenia_hoshinai_NC_014591_1`, the branch estimate for `dN/dS` is 0.3291554843643744, with the CI of [0.2208915236247295, 0.4661701189925868], the synonymous rate is `0.08756533732262452` and the non-synonymous rate is 0.09120181469800782.

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-09-17 14:19
Dear Dr. Pond, 
Thanks for your help. 
We tested the new function and got the result that corresponds to the one that you obtained.
We still have two questions (alas).

The updated `FitMG94` model reports confidence intervals (95% we assume), but brms requires SD values when using `me` method. In order to calculate SD values from these, we need sample size (https://handbook-5-1.cochrane.org/chapter_7/7_7_3_2_obtaining_standard_deviations_from_standard_errors_and.htm), but we are not sure what was the sample size in this case.

Also, we are still slightly confused by the huge discrepancy between the branch specific omega values and N/dS ratios (0.3 vs 1.04 in the B. hoshinai example above). We are slightly worried whether this discrepancy may affect our analyses.
 
Kind regards
Ivan

**Comment by spond** [comment] 2020-09-17 14:29
Dear @IvanJakovlic,

1. Those CIs are derived by profile likelihood, and you can think of them as being "Normal" confidence intervals (they are not on real data, but asymptotically they should be). For example, they will be asymmetric. You could obtain &sigma; from the confidence intervals by taking the ±1.96 &sigma; for 95% confidence intervals. So very loosely, take the CI width and divide it by 3 (to be on the conservative side) to obtain the normal std.dev.

2.  The `synonymous` and `non-synonymous` values in the example above (I was wrong in my earlier posts, they are not rates) and expected numbers of synonymous and non-synonymous substitutions per codon. So to get to one estimate of dN/dS from their ratio you need to normalize by the N:S (i.e. the number of non-synonymous sites/ number of synonymous sites). It is typically round 3 for most datasets, so you diving 1.04 by ~3 you get close to the estimated ratio.

Best,
Sergei

**Comment by IvanJakovlic** [comment] 2020-09-17 19:13
Got it!
Thanks again!

**Comment by dongzhang0725** [comment] 2020-09-18 11:39
Dear @spond ,

We compared these FitMG94 `synonymous` and `non-synonymous` values with the same group of values calculated from `AnalyzeCodonData.bf` (using `GY94W9` model). The correlation of `non-synonymous` pairs is 0.9977739, but the correlation of `synonymous` is only 0.375522. We wonder what caused the discrepancy of `synonymous` values? If we understood it right, FitMG94 are values per codon, and AnalyzeCodonData.bf are per site? However, even we scale the per codon values, this won’t affect the correlation. 

[dS comparison.xlsx](https://github.com/veg/hyphy/files/5245215/dS.comparison.xlsx)

Thanks,
Dong

**Comment by spond** [comment] 2020-09-18 12:50
Dear @dongzhang0725,

How are you getting `dS` out of `AnalyzeCodonData.bf`?

Best,
Sergei

**Comment by dongzhang0725** [comment] 2020-09-18 13:32
Dear @spond 

I relied on this tutorial for AnalyzeCodonData.bf: http://www.hyphy.org/cgi-bin/hyphy_forums/YaBB.pl?num=1122383405

First, I run the following command:

> mpirun -n 10 HYPHYMPI AnalyzeCodonData.bf -P

Then, in the interactive mode, I chose `GY94W9` model (`GY` model was the best-fit model chosen by `ModelFinder`).

I found dN and dS values in the results:
```
...
givenTree.Metapenaeus_affinis_NC_039179.synRate=19.20741067697189;
givenTree.Metapenaeus_affinis_NC_039179.nonSynRate=0.2176074966651731;
givenTree.Metapenaeus_ensis_NC_026834.synRate=15.53225016495673;
givenTree.Metapenaeus_ensis_NC_026834.nonSynRate=0.1524268696041156;
...
```

Finally, I extracted the dN and dS values from the result.

Thanks,
Dong

**Comment by spond** [comment] 2020-09-18 13:38
Dear @dongzhang0725,

A couple of things that could explain the differences

1. MG vs GY use different frequency parameterizations and FitMG94 uses a more accurate frequency estimator. 
2. What you are seeing reported by `AnalyzeCodonData.bf` are the substitutions rates, `FitMG94.bf` reports expected subs/sites (branch lengths).
3. Internal node names might be different (because of `AnalyzeCodonData.bf` will automatically reroot the tree).

I think you should decide if you want to use `rates` or `expected subs/site` and stick with that decision.

Best,
Sergei

**Comment by dongzhang0725** [comment] 2020-09-18 14:36
Dear @spond ,

I get it, Thank you very much!

Dong

**Closed** 2020-11-25 00:32 UTC
Labels: enhancement, hbl, in progress, no-issue-activity
