### ISSUE TITLE
GARD error: _LikelihoodFunction::GradientLocateTheBump

### ISSUE THREAD

**Issue by NatJWalker-Hale** [veg/hyphy#1101] opened 2020-03-04 11:51 UTC
Hi guys, 
Firstly, thanks for a great tool and secondly apologies for coming back again with another GARD error. 

I am running GARD with 32 MPI processes on the attached alignment. After finding 9 breakpoints, GARD quits with the error in the title. Experimentally, changing the model (removing rate variation) solves this, but I would prefer to not have to do this. 

Any ideas on how this might be fixed/how I could get around it?

The command was mpirun -np 32 HYPHYMPI gard --alignment 2798.nex.fa --model GTR --rv Gamma --output 2798.nex.fa.0 

I've attached the alignment concerned and the stdout and stderr from the run.

[2798.nex.fa.txt](https://github.com/veg/hyphy/files/4287086/2798.nex.fa.txt)
[test.stderr.txt](https://github.com/veg/hyphy/files/4287087/test.stderr.txt)
[test.stdout.txt](https://github.com/veg/hyphy/files/4287088/test.stdout.txt)

Thanks, 

Nat

**Comment by spond** [comment] 2020-03-04 12:33
Dear @NatJWalker-Hale,

Let me investigate. This is an internal that could be annoyingly stochastic, i.e., hard to replicate and debug. Does the error occur reliably over multiple runs for you?

Best,
Sergei

**Comment by NatJWalker-Hale** [comment] 2020-03-04 12:36
Dear @spond,  

Thanks very much for getting back to me. I've been able to replicate this over multiple runs. I believe that it is not always the same generation of the 9th breakpoint analysis, but it appears to be often/always the 9th breakpoint analysis. I did wonder if it was something to do with my compilation, but I've previously observed this on v2.3 as well (this is v2.5.1 - perhaps updating to 2.5.4 could help?)

Thanks again, 

Nat

**Comment by spond** [comment] 2020-03-04 12:38
Dear @NatJWalker-Hale,

OK, replication is great. That means I might be able to pin it down. You should update to 2.5.5 because GARD will run much faster -- I tuned some code (not as heavily used by our workhorse selection analyses) specifically with GARD in mind. I am checking your data now.

Best,
Sergei

**Comment by NatJWalker-Hale** [comment] 2020-03-04 12:39
Dear @spond, 

Great, thanks for taking a look! I will update now. 

Best, 
Nat

**Comment by spond** [comment] 2020-03-06 12:59
Dear @NatJWalker-Hale,

I was able to replicate the issue using a smaller test case. Looking at the root cause now, will update further.

Best,
Sergei

**Comment by NatJWalker-Hale** [comment] 2020-03-16 13:07
Dear @spond, 

I notice you have added a commit to 2.5.6 that addresses this, will this fix the error? If so I will download and run. 

Best, 
Nat

**Comment by spond** [comment] 2020-03-16 13:07
Dear @NatJWalker-Hale,

I **believe** the error should be fixed. Please confirm:)

Best,
Sergei

**Comment by NatJWalker-Hale** [comment] 2020-03-17 10:54
Dear @spond, 

Thank you very much! The problematic runs have now worked for 2 out of the 3 executions I tried. The other one failed with the following error 
```
Error:
Internal error
Internal error in _LikelihoodFunction::ConjugateGradientDescent. The function evaluated at current parameter values [-2017902.187576096] does not match the last recorded LF maximum [-2017832.87285804]
```
If you would like I can open a separate issue for this? 

Best, 
Nat

**Comment by spond** [comment] 2020-03-17 11:15
Dear @NatJWalker-Hale,

Making progress!! I’ll keep this issue open:)

Best,
Sergei

**Comment by spond** [comment] 2020-03-19 03:13
Dear @NatJWalker-Hale,

Please try 2.5.7.

Best,
Sergei

**Comment by NatJWalker-Hale** [comment] 2020-04-09 11:41
Dear @spond, 

Many apologies for the slow response, I was working carefully through all my problem cases with v2.5.8 just to make sure they were working. It appears to have resolved the issues I was facing before, great work and thank you very much! 

Things do seem to have slowed down a bit relatively, though. Was there any modification to the MPI routines? 

Best, 
Nat

**Comment by spond** [comment] 2020-04-09 14:06
Dear @NatJWalker-Hale,

I am surprised at the slowdown; if anything, GARD should be quite a bit faster in newer versions. Can you elaborate on what you are seeing in terms of performance? Is it total run time vs models/second kind of thing?

Best,
Sergei

**Closed** 2020-05-19 19:28 UTC
