### ISSUE TITLE
MEME - segmentation fault 

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#1074] opened 2020-02-11 13:27 UTC
Hi dear team,

Upon execution of MEME via data monkey on the below input, I receive a segmentation fault:

/var/spool/torque/mom_priv/jobs/1020960.localhost.SC: line 26: 111868 Done                    ( echo `$GENETIC_CODE;` echo $FN; echo $TREE_FN; echo 1; echo "0.1"; echo $RESULTS_FN )
     111870 Segmentation fault      (core dumped) | $HYPHY -i LIBPATH=$HYPHY_PATH $MEME >> `$PROGRESS_FILE`

Please also find attached the corresponding log file. If there is any additional information I can provide, please let me know.

[test.txt](https://github.com/veg/hyphy/files/4185861/test.txt)
[log.txt](https://github.com/veg/hyphy/files/4185870/log.txt)

Keren

**Comment by spond** [comment] 2020-02-11 16:23
Dear @halabikeren,

Thank you for reporting this issue. I was able to reproduce it and will see what is causing the errors.

Best,
Sergei

**Comment by spond** [comment] 2020-02-11 16:48
Dear @halabikeren,

Are you running this on `www.datamomkey.org` or on your own system?

Best,
Sergei

**Comment by halabikeren** [comment] 2020-02-11 17:05
Dear @spond,

I am using the data monkey web server.

Cheers,
Keren

**Comment by spond** [comment] 2020-02-11 17:51
Dear @halabikeren,

I am able to replicate the error locally, but it is stochastic (only shows up in some runs). I'll post an update when I've figured out what the problem is. 

In the meantime, the result file (compressed JSON) from a successfully completed run 
is attached.

Best,
Sergei

[results.MEME.json.zip](https://github.com/veg/hyphy/files/4187255/results.MEME.json.zip)

**Comment by spond** [comment] 2020-02-25 20:57
Dear @halabikeren,

This has been resolved in the `dev` branch and will make its way to the next release and data monkey. Thanks for reporting.

Best,
Sergei

**Closed by spond** 2020-02-25 20:57 UTC
Labels: bug, core, critical
