### ISSUE TITLE
running PRIME on cluster

### ISSUE THREAD

**Issue by jullee** [veg/hyphy#678] opened 2017-10-24 01:20 UTC
I've been able to run QuickSelectionDetection analysis in HYPHY on my home computer and departmental cluster (version 2.220161206beta(MP) for Linux on x86_64). Am I able to run a PRIME analysis from a batch file in a similar way? Or is datamonkey the only way to run a PRIME analysis? Please point me to any tutorials: I've been searching for an hour and am not finding out how to run this type of analysis. Many thanks!

**Comment by spond** [comment] 2017-10-30 22:53
Dear @jullee,

Stay tuned, this analysis is going to be ported over to version 2.3.x soon. I am finally going to write up the paper on PRIME. ETA, about 3-4 weeks.

Best,
Sergei

**Comment by stevenweaver** [comment] 2018-01-17 19:18
Closing as a duplicate of #710

**Closed by stevenweaver** 2018-01-17 19:18 UTC
