### ISSUE TITLE
Datamonkey does not recognized some sequences

### ISSUE THREAD

**Issue by K-Gutierrez** [veg/hyphy#1699] opened 2024-03-26 20:44 UTC
Hi, 

I'm currently attempting to analyze seven different genes using the aBSREL and MEME models. To prepare my data, I generated a FASTA file containing the sequences and performed codon alignment using Pal2NAL.

However, upon importing this file into the DataMonkey website, I noticed that the program failed to recognize some of the sequences. After thorough inspection, I confirmed that none of the sequences contain special characters, there are no repeated IDs, and there are no duplicated sequences. I am not sure what is the issue. 

Here is an example of my fasta file. Where 1, 2 4 are recognized by DataMonkey. 

>1
gaaagcagcaacagcaaaaccaacaccaccaacagcaaaattagcgcgggccagaccatt
agcagcgtgctgaaccagaaaaccaaagaactgccgagcctggataccctgaaaaacgcg
accacctatgcggatcagcataccggctatggcaacagcattaccatgggcgatggcagc
agcgcgaactatccggcgatttatagccgcattgatggcatggcgaccaaaaccattacc
accaccagcgatgataacggcgatagctatggccaggcgaactatgcgaacaacaacatt
cagtatcagtatgtggataccgtgcagattacctttaaaaacagcgatggcaccaccctg
gtgggcattagcaccaaccagccggcgattaacccggcgaccggcggcgtgagcgatagc
agcctggcgcgccagggctatctgtataccgtgacc
>2
gaaaacagcagcagcaaagtgagcgtgaccgaaaacagcagcagcaaaagcaaaaccacc
gcgagcatgctgaacaccagcaccaacgaactgccgagcctgcagaccctgaaaagcgcg
accgcgtatgcgaaccagcataccggcgcggcgcataacattaaaattggcaacggcagc
acccaggatcgcagcgtgttttataacagctggaccgatatgaaaaaagtgccgctgacc
ctgagcgataccgataacggcgataactatggccaggcgaactatgcgaacaacaacatt
cagtatcagtatgtggataccgtgcagattacctttaaaaacagcgatggcaccaccctg
gtgggcattagcaccaaccagccggcgattaacccggcgaccggcggcgtgagcgatagc
agcctggcgcgccagggctatctgtataccgtgacc
>3
gaaagcagcaacagcaaaaccaacaccaccaacagcaaaattagcgcgggccagaccatt
agcagcgtgctgaaccagaaaaccaaagaactgccgagcctggataccctgaaaaacgcg
accacctatgcggatcagcataccggctatggcaacagcattaccatgggcgatggcagc
agcgcgaactatccggcgatttatagccgcattgatggcatggcgaccaaaaccattacc
accaccagcgatgataacggcgatagctatggccaggcgaactatgcgaacaacaacatt
cagtatcagtatgtggataccgtgcagattacctttaaaaacagcgatggcaccaccctg
gtgggcattagcaccaaccagccggcgattaacccggcgaccggcggcgtgagcgatagc
agcctggcgcgccagggctatctgtataccgtgacc
>4
gaaaacagcagcagcaaagcgagcagcaccgaaaacagcagcagcaaaagccagaccacc
gcgagcgtgctgaacaccaacctgaacgaactgccgagcctgcagaccctgaaaagcgcg
accgcgtatgcggatcagcatgtgggctatggcaacaccctgagcatgggcgatggcagc
agcgcgaactatccggcgatgtattatcagctgggcggcgtgaccaccaaaaccctgagc
accaccagcagcgataacggcgatagctatggccaggcgaactatgcgaacaacaacatt
cagtatcagtatgtggataccgtgcagattacctttaaaaacagcgatggcaccaccctg
gtgggcattagcaccaaccagccggcgattaacccggcgaccggcggcgtgagcgatagc
agcctggcgcgccagggctatctgtataccgtgacc
>5
gaaaacagcagcagcaaagtgagcgtgaccgaaaacagcagcagcaaaagcaaaaccacc
gcgagcatgctgaacaccagcaccaacgaactgccgagcctgcagaccctgaaaagcgcg
accgcgtatgcgaaccagcataccggcgcggcgcataacattaaaattggcaacggcagc
acccaggatcgcagcgtgttttataacagctggaccgatatgaaaaaagtgccgctgacc
ctgagcgataccgataacggcgataactatggccaggcgaactatgcgaacaacaacatt
cagtatcagtatgtggataccgtgcagattacctttaaaaacagcgatggcaccaccctg
gtgggcattagcaccaaccagccggcgattaacccggcgaccggcggcgtgagcgatagc
agcctggcgcgccagggctatctgtataccgtgacc

**Comment by stevenweaver** [comment] 2024-03-26 20:46
Dear @K-Gutierrez, 

3 is a duplicate of 1. 5 is a duplicate of 2. 

Best,
Steven

**Comment by K-Gutierrez** [comment] 2024-03-26 20:50
Oh! good catch! Thank you!

**Comment by stevenweaver** [comment] 2024-03-26 21:10
No problem, glad I could help.

**Closed by stevenweaver** 2024-03-26 21:10 UTC
