### ISSUE TITLE
Standard error with Spidermonkey/BGM

### ISSUE THREAD

**Issue by silviaambros** [veg/hyphy#1179] opened 2020-06-30 07:10 UTC
I am trying to run Spidermonkey/BGM with a Protein alignment in order to do a co-variation analysis and find co-variation aminoacid sites. The problem is that the program says that there is a standard error, in detail this is the error message:
_Standard Error Message
**-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
Check errors.log for execution error details.**_

I do not know which is the problem, I run the program with the same data one year ago 
Can you help me ?
Silvia

**Comment by jzehr** [comment] 2020-06-30 12:06
Dear @silviaambros,

Are you running this analysis locally or on Datamonkey.org?

If you are running locally, can you send me the exact command you are running? 

If you are running on Datamonkey.org, can you send me the job ID file associated with the run? It should look something like http://datamonkey.org/spider-monkey/5ee1508c5a2f585a5084bf1a.

Best,
Jordan

**Comment by geofrunz** [comment] 2020-08-18 13:14
Dear  Jordan and Silvia,
I'm experiencing the same problem. I obtain a "standard error",

but no information on the actual error type. I'm running the analysis on Datamonkey, this is the ID: http://datamonkey.org/bgm/5f3bd2b1503f2f234815aeed
thank you so much
Very best regards
Giovanni

**Comment by stevenweaver** [comment] 2020-08-18 21:19
Dear @jzehr, 

Any luck finding the issue? It looks like the parameters being sent into HyPhy from datamonkey isn't properly taking into account the amino-acid datatype. 

Notice these arguments of the command being sent

```
BGM.bf --branches All --code undefined --baseline_model LG --type amino-acid
```

`branches` shouldn't be passed in at all for amino-acid, and `code` is undefined!

Best,
Steven

**Comment by stevenweaver** [comment] 2020-08-18 21:21
Dear @geofrunz, 

We will look into resolving this issue immediately. It appears BGM is a bit rogue when it comes to accepting the amino-acid datatype.

Best,
Steven

**Comment by jzehr** [comment] 2020-08-19 01:25
Dear @stevenweaver,

This is a head scratcher because I am trying to reproduce the error on DM and I dont see the arguments available that the user used.

Let me dig up a protein sequence alignment and see if I can at least get the same error to be kicked out with the ```--baseline_model LG --type amino-acid``` arguments selected.

Best,
Jordan

**Comment by jzehr** [comment] 2020-08-19 13:32
Dear @stevenweaver,

I can reproduce the error mentioned above using a different protein data set. 

Here is the job link: http://www.datamonkey.org/bgm/5f3d26f9503f2f234815e5b0, I used the same arguments mentioned above. 

Best,
Jordan

**Comment by M-LMarques** [comment] 2020-08-26 11:46
Hi everyone, 

I am experiencing the same problem as geofrunz.
I am trying to run BGM using a Protein MSA and selected the evolutionary model JTT, however my job gets aborted and no error meassage is displayed.
http://datamonkey.org/bgm/5f46461e34c53e423ae69bbb 

Any idea how to solve this?

Best
Mónica

**Comment by jzehr** [comment] 2020-08-26 12:13
Dear @M-LMarques,

Thanks for reporting on this! We have noticed some interesting behavior with this tool. We are working to address the issue.

Best,
Jordan

**Closed** 2020-08-26 16:38 UTC

**Comment by stevenweaver** [comment] 2020-08-26 16:47
Dear @silviaambros and @M-LMarques, 

This issue should now be resolved. Thank you both for reporting the issue. 

Best,
Steven
