### ISSUE TITLE
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD with errorcode 1.

### ISSUE THREAD

**Issue by SHAOHUAMUZI** [veg/hyphy#1682] opened 2024-01-19 02:03 UTC
Hello, Hyphy team:
        I use the Hyphy software package for GARD analysis, I encounter an error when running Aligned sequences .However, the same Aligned sequences for GARD analysis on DataMoney is successful， but the .NEX file provided by DataMoney triggers the same error whether for MEME or aBSRELD analysis The error message can be found at http://datamonkey.org/absrel/65a9cbe85d766b144f68ed10. 
and the Hyphy software package reports an error during GARD analysis:
![Uploading 262dff2b-1b38-43fe-9fa8-eb604be86be1.png…]()

**Comment by spond** [comment] 2024-01-19 13:21
Dear @SHAOHUAMUZI,

If you click on the "Download Log" button (sorry, not the most obvious place to look), you will see that the nature of the error is that `aBSREL` only works (by design) with a single partition dataset.

Best,
Sergei

<img width="1098" alt="image" src="https://github.com/veg/hyphy/assets/1018513/4b83e918-5cca-4690-9ae4-590c70837019">

**Comment by SHAOHUAMUZI** [comment] 2024-01-20 04:23
Dear proDear Professor：
 Thank you for your response. However, I am still unable to perform MEME analysis on the tree files generated for the three breakpoints by Datamonkey. Does MEME only support analysis on a single tree file as well?

**Comment by SHAOHUAMUZI** [comment] 2024-01-20 04:36
The MEME error message can be found at http://datamonkey.org/meme/65ab4b085d766b144f694694.But I can successfully run and analyze this .nex file using the HyPhy software package locally.

**Comment by SHAOHUAMUZI** [comment] 2024-01-20 04:37
The MEME error message can be found at http://datamonkey.org/meme/65ab4b085d766b144f694694.But I can successfully run and analyze this .nex file （from datamonkey GARD）using the HyPhy software package locally.

**Comment by spond** [comment] 2024-01-20 14:01
Dear @SHAOHUAMUZI,

Sorry to hear that Datamonkey is giving you trouble. This issue seems to stem from the same cause as https://github.com/veg/hyphy/issues/1675 

The issue is fixed in the latest `HyPhy` release, but Datamonkey may be using an older HyPhy version.

@stevenweaver : were you able to deploy a newer HyPhy version to Datamonkey?

Best,
Sergei

**Comment by stevenweaver** [comment] 2024-01-25 17:01
Dear @spond, 

`2.5.58` is currently on Datamonkey. I can update to `2.5.59` shortly. 

Best,
Steven

**Closed** 2024-04-02 00:14 UTC
Labels: no-issue-activity
