### ISSUE TITLE
Unable to run datamonkey services

### ISSUE THREAD

**Issue by andreaniml** [veg/hyphy#1660] opened 2023-10-26 14:43 UTC
Hi
I've been trying to run some analysis in Datamonkey, but so far all of the tools I've tried have outputed this message 
![image](https://github.com/veg/hyphy/assets/58482628/e620c48a-3654-4225-a52b-5c1944c02e8f)

The print is for FEL, but it happens on Absrel and Relax too, I haven't tried other ones. 

I thought that it might have been my file (even though I can select branches and there is no error message while submitting), but I get the same error with the example files from the "Help" page.

What could be the issue? Is it on my end?

**Comment by stevenweaver** [comment] 2023-10-26 14:47
It's due to the issue described at https://github.com/veg/hyphy/issues/1651#issuecomment-1764976438. Datamonkey should be running again. 

Dupe of #1651

**Closed by stevenweaver** 2023-10-26 14:47 UTC
