### ISSUE TITLE
Branch is "not a supported object type in call" when using MEME

### ISSUE THREAD

**Issue by pekarj** [veg/hyphy#1292] opened 2021-02-25 01:06 UTC
Hi all,

I'm trying to check selection on a SARS-CoV-2 dataset using MEME. I'm using a mac and HyPhy version `HYPHY 2.5.8(MP) for Darwin on x86_64`. I've been getting the following error regardless of whether I just analyze leaves or do all branches: 

```
### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) =  -929.63, AIC-c = 17746.18 (7873 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) =     -inf, AIC-c =      inf (7880 estimated parameters)
* non-synonymous/synonymous rate ratio for *background* =   0.9165
* non-synonymous/synonymous rate ratio for *test* =   1.0000

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) =     -inf
* non-synonymous/synonymous rate ratio for *background* =   0.8430
* non-synonymous/synonymous rate ratio for *test* =   1.0000
Error:
'meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020' is not a supported object type in call to SetParameter(meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020, MODEL, meme.bsrel);

Function call stack
1 :  SetParameter(meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020, MODEL, meme.bsrel);

-------
2 :  ExecuteCommands("SetParameter (`id`."+model.ApplyModelToTree.list[model.ApplyModelToTree.b]+",MODEL,"+model.ApplyModelToTree.apply_model+")", /Users/jonathanpekar/opt/anaconda3/lib/hyphy/TemplateBatchFiles/libv3/models/);
-------
3 :  model.ApplyModelToTree("meme.site_tree_bsrel",meme.trees[meme.partition_index],None,meme.model_to_branch_bsrel);
-------

Check errors.log for execution error details.
```

The error log says the following:

```
Error:'meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020' is not a supported object type in call to SetParameter(meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020, MODEL, meme.bsrel);
'meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020' is not a supported object type in call to SetParameter(meme.site_tree_bsrel.hCoV_19/SriLanka/COV53/2020, MODEL, meme.bsrel);
```

I'm unsure of what the issue is. Thoughts? I've included the relevant alignment and tree below. 

[ncov_global.aln.edited.tree.zip](https://github.com/veg/hyphy/files/6039842/ncov_global.aln.edited.tree.zip)
[ncov_global.aln.E.fasta.zip](https://github.com/veg/hyphy/files/6039843/ncov_global.aln.E.fasta.zip)

Thank you!

Best,
Jonathan

**Comment by stevenweaver** [comment] 2021-02-25 02:59
Dear Jonathan, 

It appears that it is due to `\` in header descriptions. I was able to reproduce your issue with the latest version of HyPhy, and progress beyond this point once I removed all `\` and `-` from the header descriptions in the MSA and tree files. 

I'll keep this issue open as there should at least be a warning of some sort for not supporting these characters in HyPhy. 

Best,
Steven

**Comment by spond** [comment] 2021-02-25 03:06
Thanks @stevenweaver! I was just looking into it. I think the naming issue is due to the presence of a single '.' in one sequence name. I'll diagnose further. Version 2.5.29 fixes a number of idiosyncrasies from previous versions, but apparently not all. 

Also, the following warning is now displayed:

-------
>[WARNING] This dataset contains 3858 duplicate sequences. Identical
sequences do not contribute any information to the analysis and only
slow down computation. Please consider removing duplicate or 'nearly'
duplicate sequences, e.g. using
https://github.com/veg/hyphy-analyses/tree/master/remove-duplicates
prior to running selection analyses
-------

I've compressed the dataset to 55 unique sequences and ran MEME on it. There is no evidence of selection. I'll keep the issue open like @stevenweaver suggests to fix the naming issue.

**Comment by pekarj** [comment] 2021-02-25 03:23
Thanks! I'm having an issue installing hyphy-analyses, but I'll make a new issue with that. I think it's mac-related (probably similar to the tn93 issue I had before).

**Comment by spond** [comment] 2021-02-25 03:27
Dear @pekarj,

Actually not that I've looked into it, there is an idiosyncratic HyPhy naming convention which does not gracefully handle `.` characters in sequence names. I'll add some code to MEME and other selection analyses to deal with that. Will close the issue when done. `/` characters are OK in recent versions.

Best,
Sergei

**Comment by wook2014** [comment] 2021-02-26 08:17
Dear @spond , I have meet up with a problem same as @pekarj 

`### Obtaining branch lengths and nucleotide substitution biases under the nucleotide GTR model
* Log(L) = -5530.53, AIC-c = 12051.59 (495 estimated parameters)

### Obtaining the global omega estimate based on relative GTR branch lengths and nucleotide substitution biases
* Log(L) =     -inf, AIC-c =      inf (502 estimated parameters)
* non-synonymous/synonymous rate ratio for *test* =   0.9165

### Improving branch lengths, nucleotide substitution biases, and global dN/dS ratios under a full codon model
* Log(L) = -5372.52
* non-synonymous/synonymous rate ratio for *test* =   0.7699
Error:
'meme.site_tree_bsrel.20200110061_2020-1-10_Wuhan_S' is not a supported object type in call to SetParameter(meme.site_tree_bsrel.20200110061_2020-1-10_Wuhan_S, MODEL, meme.bsrel);

Function call stack
1 :  SetParameter(meme.site_tree_bsrel.20200110061_2020-1-10_Wuhan_S, MODEL, meme.bsrel);

-------
2 :  ExecuteCommands("SetParameter (`id`."+model.ApplyModelToTree.list[model.ApplyModelToTree.b]+",MODEL,"+model.ApplyModelToTree.apply_model+")", /data/home/wuk/miniconda3/envs/phylo/lib/hyphy/TemplateBatchFiles/libv3/models/);
-------
3 :  model.ApplyModelToTree("meme.site_tree_bsrel",meme.trees[meme.partition_index],None,meme.model_to_branch_bsrel);
-------

Check errors.log for execution error details.

Check messages.log for diagnostic messages.
nohup: ignoring input`

the whole file: [meme.log](https://github.com/veg/hyphy/files/6048088/meme.log)

This error occurs when I uses a version of hyphy which I have installed in December,2020 through conda.  Most of the sequences were downloaded from Gisaid.org, so the sequence name includes some special characters like `/` and `|`.  I have updated my hyphy version in conda on Feb 26th, 2021. I found the version information showed here is still
`                     /HYPHY 2.5.1(MP) for Linux on x86_64\
***************** TYPES OF STANDARD ANALYSES *****************`

which is the same as I update before. And I have several questions:
1. How to see the hyphy version?  hyphy -v or hyphy --version seems not to work.  Help document have no information on getting the version information too.  Interactive command line shows "2.5.1(MP)", log file shows "Analysis Version: 2.1.1", anaconda.org shows it is 2.5.29. (I am nor sure it is from bioconda which is 2.5.29 because I found genomedk is also in my source channel list which the version is 2.5.1)
2. Which character is league and which is illeague in seq names? what other requirement have in sequence except no stop codon is allowed. I noticed some sequences have `N` , which translated  into `?` in MEGAX. I am afraid that this may lead to error. I also find that in the fasta file that @pekarj have provided, some seqs only contains `-`. is that ok for hyphy?

**Comment by spond** [comment] 2021-02-26 10:32
Dear @wook2014,

Version 2.5.1 is over 1 year old; cold you please update to a current version and try again? BioConda has version 2.5.29 at the moment. You can always install directly from source (follow README file). I don't personally use conda -- @davebx can you assist here?

1. `hyphy --version` will tell you the version of the HyPhy binary.
2. The only character in sequence names that HyPhy doesn't like (2.5.29 at least) is `.` (period). `N` is OK is sequence data.

Best,
Sergei

**Comment by davebx** [comment] 2021-02-26 14:19
@wook2014, the ideal way to get an environment with the right version of HyPhy is with the following command:

`conda create -y --name __hyphy@2.5.29 && conda activate __hyphy@2.5.29`

After that command completes, you should only have one HyPhy in your `$PATH`, which should be version 2.5.29

**Closed** 2021-05-05 00:44 UTC
Labels: no-issue-activity
