### ISSUE TITLE
Error in consecutive generation of likelihood functions (only in certain HyPhy versions)

### ISSUE THREAD

**Issue by halabikeren** [veg/hyphy#706] opened 2017-11-27 14:08 UTC
Dear HyPhy team,

When I attempt to generate two likelihood functions one after another, I receive an error:

`Not a supported listener type in call to bool hyphy_global_objects::UnregisterChangeListenerForDataFilter(long int, BaseRef)`

Here is the code I am using to reproduce the issue:

```
T1str = "(A:1,B:1,(C:1):2);";
T2str = "(A:1,B:1,(C:0.5):2);";

// load the sequence data
DataSet data = ReadFromString (
"
>A
1
>B
1
>C
0
"
);
DataSetFilter dataFilter = CreateFilter (data,1);

// model setting
Freqs = {{0.5},{0.5}};
global mu = 1;
RateMatrix = {{*,mu*t}
			  {mu*t,*}};
// load the model on the tree 
Model M = (RateMatrix, Freqs);

Tree T1 = T1str;
Tree T2 = T2str;

// first LF creation
LikelihoodFunction LF = (dataFilter, T1, dataFilter, T2);

Tree T1 = T1str;
Tree T2 = T2str;

// second LF creation
LikelihoodFunction LF = (dataFilter, T1, dataFilter, T2);
```

**Important note:** This problem occurs with 2.3.5 and 2.3.4, but not with hyphy 2.2.7

Thanks!
Keren

**Comment by spond** [comment] 2017-11-27 15:07
Dear @halabikeren,

This error was caused by an issue resolved in 2.3.7 (current release). I was able to confirm it with your example code, which runs without issues in v2.3.7

Best,
Sergei

**Closed** 2018-01-17 18:50 UTC
Labels: bug, core, hbl, review
