### ISSUE TITLE
Hyphy won't open tree fill but FigTree does? Whats wrong? 

### ISSUE THREAD

**Issue by michael-steffen** [veg/hyphy#259] opened 2015-02-23 22:58 UTC
When trying to upload my tree file I am getting an error saying "Could not open file M with mode r"

What does this mean? My tree opens up fine in FigTree.

THanks,
Mike

**Comment by spond** [comment] 2015-02-23 23:08
Hi Mike,

Just to clarify: you are getting this error when you are uploading a file to Datamonkey? Can you please provide more details

1. Which analysis?
2. Is the tree included as a part of the alignment file? 
3. What format is the alignment file in?

Sergei

**Comment by michael-steffen** [comment] 2015-02-24 00:20
Thanks for the quick response. I am trying to do a branchsiteREL. The data
set is too large for similar analysis in data monkey.

It is not included in the alignment file, but the method seems to be asking
for an alignment file (which opens fine), and a separate tree file.

The format is in newick, export from geneious.

Thanks,
Mike

On Mon, Feb 23, 2015 at 5:08 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Mike,
>
> Just to clarify: you are getting this error when you are uploading a file
> to Datamonkey? Can you please provide more details
>
>    1. Which analysis?
>    2. Is the tree included as a part of the alignment file?
>    3. What format is the alignment file in?
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/259#issuecomment-75658061>.
>



-- 
Michael A. Steffen
PhD. Candidate
Department of Biological Sciences
800 S. Tucker Drive
University of Tulsa
Tulsa, OK 74104
Phone (708) 738-1491

**Comment by spond** [comment] 2015-02-24 00:24
Hi Mike,

OK, I have never seen this error before from HyPhy. Are you running a command line version or a GUI version (and if so, what platform)?

Sergei

**Comment by michael-steffen** [comment] 2015-02-24 00:46
Its on the GUI on a Mac.

That is the error I get when I just try to upload a tree into hyphy. When I
go through the analysis, I get a different error.

Attached are images of the error.

On Mon, Feb 23, 2015 at 6:24 PM, Sergei Pond <notifications@github.com>
wrote:

> Hi Mike,
>
> OK, I have never seen this error before from HyPhy. Are you running a
> command line version or a GUI version (and if so, what platform)?
>
> Sergei
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/veg/hyphy/issues/259#issuecomment-75671196>.
>



-- 
Michael A. Steffen
PhD. Candidate
Department of Biological Sciences
800 S. Tucker Drive
University of Tulsa
Tulsa, OK 74104
Phone (708) 738-1491

**Comment by stevenweaver** [comment] 2015-02-24 21:17
Hi Mike, 

Unfortunately, you cannot attach images to issues through email. 
Can you upload them on this issue page itself?

Thanks,
Steven

**Comment by michael-steffen** [comment] 2015-02-24 21:29
Oh, thought I was communication through email. 
![screen shot 2015-02-23 at 6 45 55 pm](https://cloud.githubusercontent.com/assets/10971041/6359576/d71bd2b8-bc39-11e4-911d-39746dfa3d52.png)
![screen shot 2015-02-23 at 6 46 17 pm](https://cloud.githubusercontent.com/assets/10971041/6359575/d71aa348-bc39-11e4-97e1-9a92ead6da50.png)

**Comment by spond** [comment] 2015-02-24 21:31
Hi Mike,

This bug is caused by files with "too long" filenames (according to the old API that HyPhy GUI is using). If you rename your file to be less than 32 characters, the error should go away. This issue will be resolved with the next major release of HyPhy, when a new interface will be introduced.

Sergei

**Comment by stevenweaver** [comment] 2016-02-23 18:27
Closing this issue since it pertains to HyPhy 2, and the next major release of HyPhy will not include this interface.

**Closed by stevenweaver** 2016-02-23 18:27 UTC
Labels: Bug
