### ISSUE TITLE
{LEISR} positive log-likelihood due to infinite-like parameters

### ISSUE THREAD

**Issue by benjamin-elusers** [veg/hyphy#1461] opened 2022-03-02 12:35 UTC
Hi,

I have been trying to infer site-specific evolutionary rate for every proteins from yeast (_S. cerevisiae S288C_) using **HyPhy LEISR** method. Unfortunately, I have encountered the same type of error repeatedly:
> Error:
> Internal error
> Internal error: Encountered a positive log-likelihood (2.8566e-12) at evaluation 303588, mode 0, template 0. This is usually a consequence of 'infinite-like' parameter values

Basically, I have ~6500 alignment composed of >1K sequences obtained from the sequencing of 1011 isolated _S. cerevisiae_ strains. 

I've already processed about half of the proteome (3615). 
Out of those, 2044 jobs failed because of that specific error and 1591 jobs seemed to have finished returning inferred rates.
I could not see any particular bias in terms of sequence length, or number of in/variable sites in the alignment that could trigger this.

You will find below the traceback of that error in one of the job (see also attachments) if that can be of any help.

_Note:_
_The genomic sequences were initially mapped on the reference genome of S.cerevisiae S288C R64.1.1._
_The open reading frame were extracted and translated to protein sequences so there are no gaps in those alignment_
_However, nearly-all sequences ends with a STOP codon translated to (*) and they may contain additional STOP codons or sometimes undetermined amino acid (X)_
```
Function call stack
1 :  LFCompute(leisr.site_likelihood, _xxres);
Standard input redirect:
Empty Associative List
-------
2 :  CovarianceMatrix(parameters.GetProfileCI.mx, *lf);
-------
3 :  [namespace = kAXAcLYG] profile=parameters.GetProfileCI(utility.getGlobalValue("leisr.site_model_scaler_name"),lf,0.95);
-------
4 :  [namespace = mpi.RgoDcvub] Call(result_callback,0,Eval(job+'('+Join(",",utility.Map(arguments,"_value_","utility.convertToArgumentString (_value_)"))+')'),arguments);
-------
5 :  mpi.QueueJob(leisr.queue,"leisr.handle_a_site",{"0":"leisr.site_likelihood","1":alignments.serialize_site_filter((leisr.filter_specification[leisr.partition_index])[terms.data.name],(_pattern_info_[utility.getGlobalValue("terms.data.sites")])[0]),"2":leisr.partition_index,"3":_pattern_info_,"4":leisr.site_model_mapping},"leisr.store_results");
-------
6 :  Call("utility.ForEachPair.CB",utility.ForEachPair.key,object[utility.ForEachPair.key]);
-------
7 :  utility.ForEachPair(leisr.site_patterns,"_pattern_","_pattern_info_",'
            mpi.QueueJob (leisr.queue, "leisr.handle_a_site", {"0" : "leisr.site_likelihood",
                                                            "1" : alignments.serialize_site_filter
                                                               ((leisr.filter_specification[leisr.partition_index])[terms.data.name],
                                                               (_pattern_info_[utility.getGlobalValue("terms.data.sites")])[0]),
                                                            "2": leisr.partition_index,
                                                            "3" : _pattern_info_,
                                                            "4" : leisr.site_model_mapping
                                                            },
                                                            "leisr.store_results");
        ');
-------
```
I am uncertain whether this is a bug or if it can be 'fixed'. 
Looking through other issues it seems like a numerical precision type of problem. 
But I have not seen any option to prevent the estimation of the parameters to explode and avoid getting a positive log-likelihood.

I will appreciate any suggestion that you think may help (e.g even a pointer to where to look in the source code)

Thanks a lot.

---

Here are the example input files (alignment and tree) used to generate this error. 
It also contains the log file containing all the output from HyPhy.

[YLL013C.zip](https://github.com/veg/hyphy/files/8169417/YLL013C.zip)

Operating System: Linuxmint 20.3 (Ubuntu 20.04 LTS)
Processors: 16 (8 cores)
RAM: 128Gb
HyPhy version: 2.5.1 Linux MPI
Command:
`hyphy leisr CPU=10 YLL013C_strains_only.fasta YLL013C_tree.newick "Protein" "LG" "Gamma" &> YLL013C.log`

**Comment by spond** [comment] 2022-03-02 18:25
Dear @benjamin-elusers,

It seems like that the alignment you provided includes a site with `*` characters. HyPhy seems to be throwing errors at those positions, as `*` is not a valid character. If you remove the `*` characters, the calculation will proceed normally. I'll investigate why an error is not thrown.

Best,
Sergei

**Comment by benjamin-elusers** [comment] 2022-03-03 19:59
Dear @spond ,

Thank you so much for your answer. 

I was suspecting that this could be an issue but I could not see the connection with the likelihood being positive.
Anyhow, I've tried that example again after removing the final STOP codon in all sequences and it indeed proceed normally as you mentioned. I guess this issue can be marked as solved.

Though, I do have some alignments where few yeast strains may have acquired an early STOP codon, which will be marked with a **"*"** symbol in their sequence.

I will re-run all the failed jobs and verify if that did the trick for all of them, and eventually reopen the issue if some other error comes up.

**Comment by spond** [comment] 2022-03-03 20:04
Dear @benjamin-elusers,

Keep the issue open for now. `*` is not a valid alignment character for HyPhy, so I am a bit puzzled that there is no error generated or that it was not filtered out.

Best,
Sergei

**Comment by benjamin-elusers** [comment] 2022-03-03 20:10
Sure I will reopen it.
I will try running it with the version 2.5.3 just in case. (as I was using 2.5.1)

**Comment by spond** [comment] 2022-03-03 20:11
Dear @benjamin-elusers,

The issue is still there in the most recent version (2.5.36)

Best,
Sergei

**Comment by spond** [comment] 2022-03-25 16:24
Dear @benjamin-elusers,

I was able to resolve the issue (will be fixed in the upcoming release).

1. `*` means fully unresolved amino-acid (same as `?`).

2. A column with fully  unresolved amino-acids yields the log likelihood of `1` for any parameter values, i.e. contains no information about the rates (as you would expect).

3. The maximum likelihood estimate for the rate parameter is therefore not defined in any meaningful sense. This can be viewed as having an "infinite" confidence interval.

4. When HyPhy was trying to compute the CI for this "unresolved" site, it was setting the rate parameter to very high values (~10000) and running into numerical issues (hence warning).

5. In the next release, I added a numerical stabilization correction for matrix exponential calculations, and it takes care of the warning.

The "unresolved" site (880) now shows this (and the expected infinite CI and `0` log L)

```
|      Site      |   Partition    |Rel. rate (MLE) |95% profile likelihood CI| Log(L) global  |  Log(L) local  |
|:--------------:|:--------------:|:--------------:|:-----------------------:|:--------------:|:--------------:|

...
|      880       |       1        |     0.013070   |      0.00 : 10000.00    |     -0.000     |     -0.000     |

```   
  
Best,
Sergei

**Closed by spond** 2022-03-25 16:24 UTC

**Comment by benjamin-elusers** [comment] 2022-03-26 20:41
Dear @spond, 

Thank you very much for your thorough investigation and detailed explanations.
That was really helpful for me.

I look forward to get the patched version soon.
Best
