### ISSUE TITLE
BGM ERROR

### ISSUE THREAD

**Issue by zareenfatima** [veg/hyphy#282] opened 2015-04-27 22:42 UTC
please please tell why am I getting this error while running BGM analysis?

Error:
The left hand side expression does not contain an object reference in the following context: 'BGM gen_bgm=<ERROR HERE>(discreteNodes,continuou'

Function call stack
1 : BGM gen_bgm=(discreteNodes,continuousNodes)
-------
2 : ml_bgm_results=runBGM(_bgm_data)
-------

**Comment by ArtPoon** [comment] 2015-04-27 22:53
This is probably a versioning error that was recently fixed.  Can you please pull a fresh copy of HyPhy from the repo and see if that fixes this bug?

**Comment by ArtPoon** [comment] 2015-04-27 23:17
Duplicate of #266

**Comment by spond** [comment] 2015-04-28 00:00
If this is a Datamonkey error, we need to patch the BFs there. Art, can you work with Steven to do this please?

**Comment by ArtPoon** [comment] 2015-04-28 00:07
I'm pretty certain that we patched the Datamonkey scripts a while ago.

**Comment by stevenweaver** [comment] 2015-04-28 00:39
Upon further inspection, the datamonkey scripts are working as intended. 

The issue seems to be that the web server is not starting the bgm scheduler. Once the scheduler is started manually, BGM works as intended.

**Comment by zareenfatima** [comment] 2015-04-28 22:18
Thank you for your comments. updating the software worked.

**Comment by ArtPoon** [comment] 2015-04-28 22:43
Glad that worked out.  E-mail me if you have any questions about using BGMs in HyPhy.  There are more features than advertised and some more documentation in `tests/hbltests/BayesianGraphicalModels/TestBGM.bf`.

**Closed by ArtPoon** 2015-04-28 22:43 UTC
