### ISSUE TITLE
site selection MEME error

### ISSUE THREAD

**Issue by ban2224** [veg/hyphy#1439] opened 2021-12-11 02:02 UTC
What does this error mean? 

openmpi/gnu(3):ERROR:105: Unable to locate a modulefile for 'openmpi/gnu/3.0.2'
/var/spool/torque/mom_priv/jobs/1903207.new-silverback.SC: line 30: mpirun: command not found

**Comment by spond** [comment] 2021-12-11 15:08
Dear @ban2224,

We are in the process of a major cluster upgrade, and it seems like there are some "growing pains" with the Datamonkey service. We will attempt to resolve them as quickly as possible. Stay tuned.

Best,
Sergei

**Comment by stevenweaver** [comment] 2021-12-11 18:37
Dear @ban2224, 

We performed maintenance on our computing cluster that resulted in a disruption of services. The site should be operating as expected now. 

Best,
Steven

**Comment by stevenweaver** [comment] 2021-12-11 18:38
Duplicate of #1437

**Closed by stevenweaver** 2021-12-11 18:38 UTC
