### ISSUE TITLE
SLAC OUTPUT TABLE

### ISSUE THREAD

**Issue by AdenoV** [veg/hyphy#844] opened 2018-09-28 10:13 UTC
Dear sir or madame,
I ran an SLAC analysis and it has finished but I not able to export table results. This is the output webpage:
http://staging.datamonkey.org/slac/5baa32518048131dacf5a76d 
I hope you can help me. Thank you very much in advance.
Regards,
Jenny

**Comment by rdvelazquez** [comment] 2018-09-28 13:49
Dear Jenny,

Thanks for bringing this to our attention. We will look into why the "export to csv" button isn't working and address the issue. 

In the meantime, I saved the json output and used vision.hyphy.org to visualize the results and was able to export the csv. I've attached the exported file for your use. 
[export.csv.zip](https://github.com/veg/hyphy/files/2428407/export.csv.zip)

Thanks again for letting us know. We really appreciate it!

Best,
Ryan

**Comment by AdenoV** [comment] 2018-09-28 14:21
Dear Ryan!


Thank you so much for sent me the file, you helped me a lot in my busy day!


Jenny


Jennifer Risso Ballester
PhD Student Evolución y Salud
Instituto Cavanilles de Biodiversidad y Biologia Evolutiva

________________________________
De: Ryan Velazquez <notifications@github.com>
Enviado: viernes, 28 de septiembre de 2018 15:49:59
Para: veg/hyphy
Cc: Jennifer Risso Ballester; Author
Asunto: Re: [veg/hyphy] SLAC OUTPUT TABLE (#844)


Dear Jenny,

Thanks for bringing this to our attention. We will look into why the "export to csv" button isn't working and address the issue.

In the meantime, I saved the json output and used vision.hyphy.org to visualize the results and was able to export the csv. I've attached the exported file for your use.
export.csv.zip<https://github.com/veg/hyphy/files/2428407/export.csv.zip>

Thanks again for letting us know. We really appreciate it!

Best,
Ryan

**Comment by AdenoV** [comment] 2018-10-08 10:40
Dear Ryan,
Now, SLAC webpage results does not load.

http://datamonkey.org/slac/5bb1d4cb334d3c77845b6fdf
and
https://www.datamonkey.org/slac/5bb38f7a16392059437f6777 

Regards,
J

**Comment by rdvelazquez** [comment] 2018-10-08 14:43
Dear Jenny,

I'm not sure why the webpage isn't loading for those particular jobs. I'm re-running both jobs to see if I can locate and address the issue. 

In the interim, the two results files are attached below. You can view the results on vision.hyphy.org:
[slacResults.zip](https://github.com/veg/hyphy/files/2456393/slacResults.zip)

I'll let you know when the issue with viewing the results pages is addressed.

Best,
Ryan

**Comment by AdenoV** [comment] 2018-10-08 15:30
Dear Ryan,
The same problem occurs with:
https://www.datamonkey.org/slac/5bbb41f91639205943803727
¿How can I obtain the results that you can sent me?
Thanks a lot again.
Best,
JR

**Comment by rdvelazquez** [comment] 2018-10-08 19:49
Dear Jenny,

I located the issue. The problem is caused by the results json files being too large for our current database structure. The issue has been addressed in our staging instance of datamonkey (staging.datamonkey.org). You can use that site for your SLAC analyses and I'll let you know when the changes get pushed to the main datamonkey instance (datamonkey.org).

> How can I obtain the results that you can sent me?

There's no way for you to get the results from the site as is. I would just re-run them on the staging instance.

Best,
Ryan

**Comment by AdenoV** [comment] 2018-10-09 10:48
Ryan,
Can I use this site for running GARD analyses?
Best,
JR

**Comment by rdvelazquez** [comment] 2018-10-09 11:59
JR,
The staging site can be used for all the same analyses as the main site. It is just the codebase as it is developed, prior to being officially released. Good luck with your analyses and don't hesitate to let us know if you have any additional questions.
Best,
Ryan

**Closed** 2018-11-01 19:35 UTC
