### ISSUE TITLE
Can't seem to get over initialization phase for Analysis

### ISSUE THREAD

**Issue by Leki-10** [veg/hyphy#1500] opened 2022-08-01 18:35 UTC
Hi Sergei Pond,

I have been trying to use DataMonkey to analyze a set of 25 variants of a gene. Sequences with variation occurring over 30% were used in a nucleotide alignment (only coding sequence in multiple of 3) and I want to try different methods available on DataMonkey to estimate a directional selection. There's an issue that I am consistently facing after successfully uploading my nucleotide alignment though; please see the attached files, where the method is successfully initialized, but then fails to give any output due to an unknown error. This is happening with every method available. Please can you help me learn how can I get over this issue and analyze my alignments further?

Thank you for your time in advance.
Leki

![DataMonkey_issue1](https://user-images.githubusercontent.com/110419911/182219212-ad1b3f83-1143-461b-b3db-35a9ef1b2063.png)

![DataMonkey_issue2](https://user-images.githubusercontent.com/110419911/182219239-2d45bf3d-8edc-4e97-8108-ea8b832e9479.png)

![DataMonkey_issue3](https://user-images.githubusercontent.com/110419911/182219261-e1493995-8de7-4712-aff2-03d57ac77426.png)

**Comment by nicer626** [comment] 2022-08-02 09:10
I  had the same problem.

**Comment by stevenweaver** [comment] 2022-08-02 16:39
Duplicate of #1501. Closing.

**Closed by stevenweaver** 2022-08-02 16:39 UTC

**Comment by nicer626** [comment] 2022-08-03 01:25
> [#1501 的副本](https://github.com/veg/hyphy/issues/1501)。关闭。

Dear Steven weaver,

Excuse me. What can I do for it?

Thank you for your time in advance.
Ziwen Zhang

**Comment by Leki-10** [comment] 2022-08-03 06:43
Hi Steven,

Thanks for trying to sort out the issue. The issue still persists though, I spent entire yesterday to run my tasks, but doesn't seem to get over initialization phase. Also, the queue seems to be quite lengthy, please can you let me know how long does it usually take to run an FEL or MEME method? If I put my job in the queue, can I possibly close the system and get a link to my results on email provided with the task?

Much appreciate your help over this forum, thanks a lot!

Best regards
Leki
![DM_2](https://user-images.githubusercontent.com/110419911/182541429-cefdef9b-b16a-49b8-bdad-effa9ff05371.png)
![DM_1](https://user-images.githubusercontent.com/110419911/182541458-603266a2-75b9-4df4-94ad-288718a9bd6a.png)
