### ISSUE TITLE
Problem running SLAC

### ISSUE THREAD

**Issue by rahmedbg** [veg/hyphy#1656] opened 2023-10-16 04:14 UTC
Every time I want to run SLAC , following message is shown-
We're sorry, there was an error processing your job. Please try again, or visit
[our GitHub issues page](http://github.com/veg/hyphy/issues/)
and create an issue if the issue persists.

My job URL is 

https://www.datamonkey.org/slac/652cb715353125059b65cc4e

**Comment by 3032281342** [comment] 2023-10-16 09:51
Yes,today I also have this error!!!Do you solve it？

**Comment by stephenshank** [comment] 2023-10-16 13:29
Dear @rahmedbg and @3032281342,

Thanks for reporting this issue. Can you please try again?

Regards,
Stephen

**Comment by stevenweaver** [comment] 2023-10-16 17:43
Duplicate of #1651

**Closed by stevenweaver** 2023-10-16 17:43 UTC

**Comment by rahmedbg** [comment] 2023-10-16 17:44
Thanks, now its' working!
