### ISSUE TITLE
FUBAR still running although I have received confirmation e-mail of a completed job

### ISSUE THREAD

**Issue by mhdatefzayed** [veg/hyphy#802] opened 2018-05-22 22:46 UTC
Hi,
Although yesterday I received e-mail stating that the job 5b03066ce874d6400f1f4b89 has completed, but I did not find any results and the analysis still running till now at http://datamonkey.org/fubar/5b03066ce874d6400f1f4b89. 
Thanks in forward.

**Comment by stevenweaver** [comment] 2018-05-23 13:52
Dear @mhdatefzayed, 

This was reported by #799. Please download your results from this [url](http://octamonkey.datamonkey.org/issues/5b03066ce874d6400f1f4b89.FUBAR.json) and view them using [hyphy-vision](http://vision.hyphy.org/methods/fubar/). 

@veg/datamonkey will work on resolving the issue shortly.

Best,
Steven

**Comment by stevenweaver** [comment] 2018-05-23 13:53
Closing issue as it is a duplicate of #799.

**Closed by stevenweaver** 2018-05-23 13:53 UTC
